[package]
name = "yjc"
version = "0.0.1"
authors = ["Yisar"]
edition = "2018"
description = "tiny javascript compiler"
license = "MIT"

[dependencies]
json = "0.12"
regex = "1.11.1"

[profile.release]
panic = 'abort'
